CREATE TABLE pokemon_data (
    national_number INT,
    gen VARCHAR(2),
    english_name VARCHAR(255),
    primary_type VARCHAR(255),
    secondary_type VARCHAR(255),
    classification VARCHAR(255),
    percent_male DECIMAL(5,2),
    percent_female DECIMAL(5,2),
    height_m DECIMAL(4,1),
    weight_kg DECIMAL(5,1),
    capture_rate INT,
    hp INT,
    attack INT,
    defense INT,
    speed INT,
    abilities_0 VARCHAR(255),
    abilities_1 VARCHAR(255),
    abilities_special VARCHAR(255),
    is_sublegendary TINYINT(1),
    is_legendary TINYINT(1),
    is_mythical TINYINT(1),
    evochain_0 VARCHAR(255),
    evochain_2 VARCHAR(255),
    evochain_4 VARCHAR(255),
    mega_evolution VARCHAR(255),
    description TEXT
);
